DROP TABLE REPORT CASCADE CONSTRAINTS;
-----------------------------------------------------------

CREATE TABLE REPORT (
   P_NO   NUMBER(10)      NOT NULL,
   P_TYPE   NUMBER(10)      NOT NULL,
   P_TITLE   VARCHAR2(100)      NOT NULL,
   P_CONTENT   VARCHAR2(4000)      NOT NULL,
   P_DATE   DATE   DEFAULT SYSDATE   NOT NULL,
   P_STATUS   VARCHAR2(100)   DEFAULT 'Y'   NOT NULL,
   P_BNO   NUMBER(10)      NOT NULL,
   P_RECEIVER   VARCHAR2(100)      NOT NULL,
   P_REPORTER   VARCHAR2(100)      NOT NULL,
   P_BPAGE VARCHAR2(20) 	NOT NULL,
   P_MNICK VARCHAR2(100) NUT NULL ,
   P_BTYPE VARCHAR2(10) NOT NULL
);

ALTER TABLE REPORT ADD CONSTRAINT PK_REPORT PRIMARY KEY (
   P_NO
);

ALTER TABLE REPORT ADD CONSTRAINT REPORT_MEMBER_ID
FOREIGN KEY (P_RECEIVER)
REFERENCES MEMBER (M_ID);

ALTER TABLE REPORT ADD CONSTRAINT REPORT_MEMBER_ID2
FOREIGN KEY (P_REPORTER)
REFERENCES MEMBER (M_ID);

ALTER TABLE REPORT ADD CONSTRAINT REPORT_BOARD_ID
FOREIGN KEY (P_BNO)
REFERENCES BOARD (B_NO);

CREATE SEQUENCE SEQ_RNO
    START WITH 1
    INCREMENT BY 1;


  

    